apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: 1
  name: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: hello-service
    spec:
      containers:
      - image: <PATCH_ME>
        imagePullPolicy: IfNotPresent
        name: hello-service
        ports:
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
